apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-config-map
  namespace: kube-system
data:
  fluent.conf: |
    @include kubernetes.conf

    <match **>
      type remote_syslog
      host p3dlafwrkr0001.cloud.phx3.gdg
      port 514
      severity info
      tag fluentd
    </match>
  kubernetes.conf: |
    <match fluent.**>
      type null
    </match>

    <source>
      type tail
      path /var/log/containers/wp-cache*.log
      pos_file /var/log/fluentd-containers.log.pos
      time_format %Y-%m-%dT%H:%M:%S.%NZ
      keep_time_key true
      tag kubernetes.*
      format json
      read_from_head true
    </source>

    <filter kubernetes.**>
      type kubernetes_metadata
    </filter>


    <filter kubernetes.**>
      type record_transformer
      enable_ruby true
      auto_typecast true
      <record>
       brand_id ${nil}
       data: ${{"container_name" => kubernetes["container_name"], "pod_namespace" => kubernetes["namespace_name"], "pod_name" => kubernetes["pod_name"], "siteid" => kubernetes["pod_name"].gsub(/([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})/,'\1'), "message" => record["log"]}}
       datacenter "A2"
       envelope_version "1.2.1"
       environment "PROD"
       # Hostname has to be filled in dynamically
       host ${{"hostname" => ""}}
       role "BUSINESS_ANALYTICS"
       timestamp ${record["time"]}
       type mwp2-kubernetes-accesslogs
      </record>
      remove_keys log,attrs,stream,kubernetes,docker,time
    </filter>

---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: fluentd
  namespace: kube-system
  labels:
    k8s-app: fluentd-logging
    version: v1
    kubernetes.io/cluster-service: "true"
spec:
  template:
    metadata:
      labels:
        k8s-app: fluentd-logging
        version: v1
        kubernetes.io/cluster-service: "true"
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: fluentd
        image: damiansilbergleithcunniff/fluentd:accesslogs-rsyslog-v0.2
        env:
          - name: KUBERNETES_SERVICE_HOST
            value: kubernetes.default
          - name: KUBERNETES_SERVICE_PORT
            value: "443"
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: fluent-configs
          mountPath: /fluentd/etc/
          readOnly: true
        - name: varlogcontainers
          mountPath: /var/log/containers
        - name: varlogpods
          mountPath: /var/log/pods
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
      terminationGracePeriodSeconds: 30
      volumes:
      - name: fluent-configs
        configMap:
          name: fluent-config-map
      - name: varlogcontainers
        hostPath:
          path: /var/log/containers
      - name: varlogpods
        hostPath:
          path: /var/log/pods
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
